# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Wed Sep 22 10:30:31 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 749)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Globe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("None")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeCluster = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeCluster.sizePolicy().hasHeightForWidth())
        self.treeCluster.setSizePolicy(sizePolicy)
        self.treeCluster.setMinimumSize(QtCore.QSize(150, 0))
        self.treeCluster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeCluster.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeCluster.setObjectName("treeCluster")
        self.horizontalLayout_5.addWidget(self.treeCluster)
        self.tabsMain = QtGui.QTabWidget(self.centralwidget)
        self.tabsMain.setMinimumSize(QtCore.QSize(325, 0))
        self.tabsMain.setToolTip("")
        self.tabsMain.setObjectName("tabsMain")
        self.MTasks = QtGui.QWidget()
        self.MTasks.setObjectName("MTasks")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.MTasks)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbClearKey = QtGui.QGroupBox(self.MTasks)
        self.gbClearKey.setFlat(False)
        self.gbClearKey.setObjectName("gbClearKey")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.gbClearKey)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblCacheKeys = QtGui.QLabel(self.gbClearKey)
        self.lblCacheKeys.setObjectName("lblCacheKeys")
        self.horizontalLayout_7.addWidget(self.lblCacheKeys)
        self.txtCacheKeys = QtGui.QLineEdit(self.gbClearKey)
        self.txtCacheKeys.setObjectName("txtCacheKeys")
        self.horizontalLayout_7.addWidget(self.txtCacheKeys)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnGetCacheKeys = QtGui.QPushButton(self.gbClearKey)
        self.btnGetCacheKeys.setObjectName("btnGetCacheKeys")
        self.horizontalLayout.addWidget(self.btnGetCacheKeys)
        self.btnDelCacheKeys = QtGui.QPushButton(self.gbClearKey)
        self.btnDelCacheKeys.setObjectName("btnDelCacheKeys")
        self.horizontalLayout.addWidget(self.btnDelCacheKeys)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.btnFlushCache = QtGui.QPushButton(self.gbClearKey)
        self.btnFlushCache.setObjectName("btnFlushCache")
        self.verticalLayout_7.addWidget(self.btnFlushCache)
        self.verticalLayout_2.addWidget(self.gbClearKey)
        self.gbKeySearch = QtGui.QGroupBox(self.MTasks)
        self.gbKeySearch.setObjectName("gbKeySearch")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.gbKeySearch)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblKeySearch = QtGui.QLabel(self.gbKeySearch)
        self.lblKeySearch.setObjectName("lblKeySearch")
        self.gridLayout.addWidget(self.lblKeySearch, 0, 0, 1, 1)
        self.txtSearchKey = QtGui.QLineEdit(self.gbKeySearch)
        self.txtSearchKey.setObjectName("txtSearchKey")
        self.gridLayout.addWidget(self.txtSearchKey, 0, 1, 1, 1)
        self.cbRegEx = QtGui.QCheckBox(self.gbKeySearch)
        self.cbRegEx.setObjectName("cbRegEx")
        self.gridLayout.addWidget(self.cbRegEx, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.lblRegExWarning = QtGui.QLabel(self.gbKeySearch)
        self.lblRegExWarning.setWordWrap(True)
        self.lblRegExWarning.setObjectName("lblRegExWarning")
        self.verticalLayout_8.addWidget(self.lblRegExWarning)
        self.btnKeySearch = QtGui.QPushButton(self.gbKeySearch)
        self.btnKeySearch.setObjectName("btnKeySearch")
        self.verticalLayout_8.addWidget(self.btnKeySearch)
        self.pbKeySearch = QtGui.QProgressBar(self.gbKeySearch)
        self.pbKeySearch.setProperty("value", 0)
        self.pbKeySearch.setObjectName("pbKeySearch")
        self.verticalLayout_8.addWidget(self.pbKeySearch)
        self.verticalLayout_2.addWidget(self.gbKeySearch)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabsMain.addTab(self.MTasks, "")
        self.SKInfo = QtGui.QWidget()
        self.SKInfo.setObjectName("SKInfo")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.SKInfo)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtGui.QLabel(self.SKInfo)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.tabsMain.addTab(self.SKInfo, "")
        self.Stats = QtGui.QWidget()
        self.Stats.setObjectName("Stats")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Stats)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabsStats = QtGui.QTabWidget(self.Stats)
        self.tabsStats.setObjectName("tabsStats")
        self.CacheInfo = QtGui.QWidget()
        self.CacheInfo.setObjectName("CacheInfo")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.CacheInfo)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea_2 = QtGui.QScrollArea(self.CacheInfo)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 562, 540))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gbTotals = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbTotals.setObjectName("gbTotals")
        self.gridLayout_3 = QtGui.QGridLayout(self.gbTotals)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblCurrentItemsTxt = QtGui.QLabel(self.gbTotals)
        self.lblCurrentItemsTxt.setObjectName("lblCurrentItemsTxt")
        self.gridLayout_3.addWidget(self.lblCurrentItemsTxt, 1, 0, 1, 1)
        self.lblCurrentItems = QtGui.QLabel(self.gbTotals)
        self.lblCurrentItems.setObjectName("lblCurrentItems")
        self.gridLayout_3.addWidget(self.lblCurrentItems, 1, 1, 1, 1)
        self.lblHitsTxt = QtGui.QLabel(self.gbTotals)
        self.lblHitsTxt.setObjectName("lblHitsTxt")
        self.gridLayout_3.addWidget(self.lblHitsTxt, 5, 0, 1, 1)
        self.lblHits = QtGui.QLabel(self.gbTotals)
        self.lblHits.setObjectName("lblHits")
        self.gridLayout_3.addWidget(self.lblHits, 5, 1, 1, 1)
        self.lblMissesTxt = QtGui.QLabel(self.gbTotals)
        self.lblMissesTxt.setObjectName("lblMissesTxt")
        self.gridLayout_3.addWidget(self.lblMissesTxt, 6, 0, 1, 1)
        self.lblMisses = QtGui.QLabel(self.gbTotals)
        self.lblMisses.setObjectName("lblMisses")
        self.gridLayout_3.addWidget(self.lblMisses, 6, 1, 1, 1)
        self.lblFreeTxt = QtGui.QLabel(self.gbTotals)
        self.lblFreeTxt.setObjectName("lblFreeTxt")
        self.gridLayout_3.addWidget(self.lblFreeTxt, 10, 0, 1, 1)
        self.lblFree = QtGui.QLabel(self.gbTotals)
        self.lblFree.setObjectName("lblFree")
        self.gridLayout_3.addWidget(self.lblFree, 10, 1, 1, 1)
        self.lblUsedTxt = QtGui.QLabel(self.gbTotals)
        self.lblUsedTxt.setObjectName("lblUsedTxt")
        self.gridLayout_3.addWidget(self.lblUsedTxt, 11, 0, 1, 1)
        self.lblUsed = QtGui.QLabel(self.gbTotals)
        self.lblUsed.setObjectName("lblUsed")
        self.gridLayout_3.addWidget(self.lblUsed, 11, 1, 1, 1)
        self.lblItemsTxt = QtGui.QLabel(self.gbTotals)
        self.lblItemsTxt.setObjectName("lblItemsTxt")
        self.gridLayout_3.addWidget(self.lblItemsTxt, 0, 0, 1, 1)
        self.lblItems = QtGui.QLabel(self.gbTotals)
        self.lblItems.setObjectName("lblItems")
        self.gridLayout_3.addWidget(self.lblItems, 0, 1, 1, 1)
        self.lblConnectionsTxt = QtGui.QLabel(self.gbTotals)
        self.lblConnectionsTxt.setObjectName("lblConnectionsTxt")
        self.gridLayout_3.addWidget(self.lblConnectionsTxt, 2, 0, 1, 1)
        self.lblConnections = QtGui.QLabel(self.gbTotals)
        self.lblConnections.setObjectName("lblConnections")
        self.gridLayout_3.addWidget(self.lblConnections, 2, 1, 1, 1)
        self.lblCurrentConnectionsTxt = QtGui.QLabel(self.gbTotals)
        self.lblCurrentConnectionsTxt.setObjectName("lblCurrentConnectionsTxt")
        self.gridLayout_3.addWidget(self.lblCurrentConnectionsTxt, 3, 0, 1, 1)
        self.lblCurrentConnections = QtGui.QLabel(self.gbTotals)
        self.lblCurrentConnections.setObjectName("lblCurrentConnections")
        self.gridLayout_3.addWidget(self.lblCurrentConnections, 3, 1, 1, 1)
        self.lblGetsTxt = QtGui.QLabel(self.gbTotals)
        self.lblGetsTxt.setObjectName("lblGetsTxt")
        self.gridLayout_3.addWidget(self.lblGetsTxt, 7, 0, 1, 1)
        self.lblGets = QtGui.QLabel(self.gbTotals)
        self.lblGets.setObjectName("lblGets")
        self.gridLayout_3.addWidget(self.lblGets, 7, 1, 1, 1)
        self.lblSetsTxt = QtGui.QLabel(self.gbTotals)
        self.lblSetsTxt.setObjectName("lblSetsTxt")
        self.gridLayout_3.addWidget(self.lblSetsTxt, 8, 0, 1, 1)
        self.lblSets = QtGui.QLabel(self.gbTotals)
        self.lblSets.setObjectName("lblSets")
        self.gridLayout_3.addWidget(self.lblSets, 8, 1, 1, 1)
        self.lblSpaceTxt = QtGui.QLabel(self.gbTotals)
        self.lblSpaceTxt.setObjectName("lblSpaceTxt")
        self.gridLayout_3.addWidget(self.lblSpaceTxt, 9, 0, 1, 1)
        self.lblSpace = QtGui.QLabel(self.gbTotals)
        self.lblSpace.setObjectName("lblSpace")
        self.gridLayout_3.addWidget(self.lblSpace, 9, 1, 1, 1)
        self.lblThreadsTxt = QtGui.QLabel(self.gbTotals)
        self.lblThreadsTxt.setObjectName("lblThreadsTxt")
        self.gridLayout_3.addWidget(self.lblThreadsTxt, 4, 0, 1, 1)
        self.lblThreads = QtGui.QLabel(self.gbTotals)
        self.lblThreads.setObjectName("lblThreads")
        self.gridLayout_3.addWidget(self.lblThreads, 4, 1, 1, 1)
        self.lblEvicTxt = QtGui.QLabel(self.gbTotals)
        self.lblEvicTxt.setObjectName("lblEvicTxt")
        self.gridLayout_3.addWidget(self.lblEvicTxt, 12, 0, 1, 1)
        self.lblEvic = QtGui.QLabel(self.gbTotals)
        self.lblEvic.setObjectName("lblEvic")
        self.gridLayout_3.addWidget(self.lblEvic, 12, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbTotals)
        self.gbRates = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbRates.setObjectName("gbRates")
        self.gridLayout_4 = QtGui.QGridLayout(self.gbRates)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblRequestRateTxt = QtGui.QLabel(self.gbRates)
        self.lblRequestRateTxt.setObjectName("lblRequestRateTxt")
        self.gridLayout_4.addWidget(self.lblRequestRateTxt, 0, 0, 1, 1)
        self.lblRequestRate = QtGui.QLabel(self.gbRates)
        self.lblRequestRate.setObjectName("lblRequestRate")
        self.gridLayout_4.addWidget(self.lblRequestRate, 0, 1, 1, 1)
        self.lblHitRateTxt = QtGui.QLabel(self.gbRates)
        self.lblHitRateTxt.setObjectName("lblHitRateTxt")
        self.gridLayout_4.addWidget(self.lblHitRateTxt, 4, 0, 1, 1)
        self.lblHitRate = QtGui.QLabel(self.gbRates)
        self.lblHitRate.setObjectName("lblHitRate")
        self.gridLayout_4.addWidget(self.lblHitRate, 4, 1, 1, 1)
        self.lblMissRateTxt = QtGui.QLabel(self.gbRates)
        self.lblMissRateTxt.setObjectName("lblMissRateTxt")
        self.gridLayout_4.addWidget(self.lblMissRateTxt, 6, 0, 1, 1)
        self.lblMissRate = QtGui.QLabel(self.gbRates)
        self.lblMissRate.setObjectName("lblMissRate")
        self.gridLayout_4.addWidget(self.lblMissRate, 6, 1, 1, 1)
        self.lblSetRateTxt = QtGui.QLabel(self.gbRates)
        self.lblSetRateTxt.setObjectName("lblSetRateTxt")
        self.gridLayout_4.addWidget(self.lblSetRateTxt, 10, 0, 1, 1)
        self.lblGetRateTxt = QtGui.QLabel(self.gbRates)
        self.lblGetRateTxt.setObjectName("lblGetRateTxt")
        self.gridLayout_4.addWidget(self.lblGetRateTxt, 8, 0, 1, 1)
        self.lblSetRate = QtGui.QLabel(self.gbRates)
        self.lblSetRate.setObjectName("lblSetRate")
        self.gridLayout_4.addWidget(self.lblSetRate, 10, 1, 1, 1)
        self.lblGetRate = QtGui.QLabel(self.gbRates)
        self.lblGetRate.setObjectName("lblGetRate")
        self.gridLayout_4.addWidget(self.lblGetRate, 8, 1, 1, 1)
        self.lblEvicRateTxt = QtGui.QLabel(self.gbRates)
        self.lblEvicRateTxt.setObjectName("lblEvicRateTxt")
        self.gridLayout_4.addWidget(self.lblEvicRateTxt, 11, 0, 1, 1)
        self.lblEvicRate = QtGui.QLabel(self.gbRates)
        self.lblEvicRate.setObjectName("lblEvicRate")
        self.gridLayout_4.addWidget(self.lblEvicRate, 11, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbRates)
        self.gbAvgRates = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbAvgRates.setObjectName("gbAvgRates")
        self.gridLayout_2 = QtGui.QGridLayout(self.gbAvgRates)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblRequestRateAvgTxt = QtGui.QLabel(self.gbAvgRates)
        self.lblRequestRateAvgTxt.setObjectName("lblRequestRateAvgTxt")
        self.gridLayout_2.addWidget(self.lblRequestRateAvgTxt, 0, 0, 1, 1)
        self.lblRequestRateAvg = QtGui.QLabel(self.gbAvgRates)
        self.lblRequestRateAvg.setObjectName("lblRequestRateAvg")
        self.gridLayout_2.addWidget(self.lblRequestRateAvg, 0, 1, 1, 1)
        self.lblHitRateAvgTxt = QtGui.QLabel(self.gbAvgRates)
        self.lblHitRateAvgTxt.setObjectName("lblHitRateAvgTxt")
        self.gridLayout_2.addWidget(self.lblHitRateAvgTxt, 1, 0, 1, 1)
        self.lblHitRateAvg = QtGui.QLabel(self.gbAvgRates)
        self.lblHitRateAvg.setObjectName("lblHitRateAvg")
        self.gridLayout_2.addWidget(self.lblHitRateAvg, 1, 1, 1, 1)
        self.lblMissRateAvgTxt = QtGui.QLabel(self.gbAvgRates)
        self.lblMissRateAvgTxt.setObjectName("lblMissRateAvgTxt")
        self.gridLayout_2.addWidget(self.lblMissRateAvgTxt, 2, 0, 1, 1)
        self.lblMissRateAvg = QtGui.QLabel(self.gbAvgRates)
        self.lblMissRateAvg.setObjectName("lblMissRateAvg")
        self.gridLayout_2.addWidget(self.lblMissRateAvg, 2, 1, 1, 1)
        self.lblGetRateAvgTxt = QtGui.QLabel(self.gbAvgRates)
        self.lblGetRateAvgTxt.setObjectName("lblGetRateAvgTxt")
        self.gridLayout_2.addWidget(self.lblGetRateAvgTxt, 3, 0, 1, 1)
        self.lblGetRateAvg = QtGui.QLabel(self.gbAvgRates)
        self.lblGetRateAvg.setObjectName("lblGetRateAvg")
        self.gridLayout_2.addWidget(self.lblGetRateAvg, 3, 1, 1, 1)
        self.lblSetRateAvgTxt = QtGui.QLabel(self.gbAvgRates)
        self.lblSetRateAvgTxt.setObjectName("lblSetRateAvgTxt")
        self.gridLayout_2.addWidget(self.lblSetRateAvgTxt, 4, 0, 1, 1)
        self.lblSetRateAvg = QtGui.QLabel(self.gbAvgRates)
        self.lblSetRateAvg.setObjectName("lblSetRateAvg")
        self.gridLayout_2.addWidget(self.lblSetRateAvg, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbAvgRates)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.scrollArea_2)
        self.tabsStats.addTab(self.CacheInfo, "")
        self.Diagrams = QtGui.QWidget()
        self.Diagrams.setObjectName("Diagrams")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Diagrams)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.Diagrams)
        self.scrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 562, 540))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCacheUsageGraph = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCacheUsageGraph.setObjectName("lblCacheUsageGraph")
        self.verticalLayout.addWidget(self.lblCacheUsageGraph)
        self.lblHitsMissesGraph = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblHitsMissesGraph.setObjectName("lblHitsMissesGraph")
        self.verticalLayout.addWidget(self.lblHitsMissesGraph)
        self.lblGetSetGraph = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblGetSetGraph.setObjectName("lblGetSetGraph")
        self.verticalLayout.addWidget(self.lblGetSetGraph)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.tabsStats.addTab(self.Diagrams, "")
        self.ServerInfo = QtGui.QWidget()
        self.ServerInfo.setObjectName("ServerInfo")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.ServerInfo)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saServerInfo = QtGui.QScrollArea(self.ServerInfo)
        self.saServerInfo.setWidgetResizable(True)
        self.saServerInfo.setObjectName("saServerInfo")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.saServerInfo)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 562, 540))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gbServerX = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.gbServerX.setObjectName("gbServerX")
        self.gridLayout_5 = QtGui.QGridLayout(self.gbServerX)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblServerXTotalItemsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalItemsTxt.setObjectName("lblServerXTotalItemsTxt")
        self.gridLayout_5.addWidget(self.lblServerXTotalItemsTxt, 0, 0, 1, 1)
        self.lblServerXTotalItems = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalItems.setObjectName("lblServerXTotalItems")
        self.gridLayout_5.addWidget(self.lblServerXTotalItems, 0, 1, 1, 1)
        self.lblServerXItemsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXItemsTxt.setObjectName("lblServerXItemsTxt")
        self.gridLayout_5.addWidget(self.lblServerXItemsTxt, 1, 0, 1, 1)
        self.lblServerXItems = QtGui.QLabel(self.gbServerX)
        self.lblServerXItems.setObjectName("lblServerXItems")
        self.gridLayout_5.addWidget(self.lblServerXItems, 1, 1, 1, 1)
        self.lblServerXTotalConnectionsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalConnectionsTxt.setObjectName("lblServerXTotalConnectionsTxt")
        self.gridLayout_5.addWidget(self.lblServerXTotalConnectionsTxt, 2, 0, 1, 1)
        self.lblServerXTotalConnections = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalConnections.setObjectName("lblServerXTotalConnections")
        self.gridLayout_5.addWidget(self.lblServerXTotalConnections, 2, 1, 1, 1)
        self.lblServerXConnectionsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXConnectionsTxt.setObjectName("lblServerXConnectionsTxt")
        self.gridLayout_5.addWidget(self.lblServerXConnectionsTxt, 3, 0, 1, 1)
        self.lblServerXConnections = QtGui.QLabel(self.gbServerX)
        self.lblServerXConnections.setObjectName("lblServerXConnections")
        self.gridLayout_5.addWidget(self.lblServerXConnections, 3, 1, 1, 1)
        self.lblServerXHitsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXHitsTxt.setObjectName("lblServerXHitsTxt")
        self.gridLayout_5.addWidget(self.lblServerXHitsTxt, 4, 0, 1, 1)
        self.lblServerXHits = QtGui.QLabel(self.gbServerX)
        self.lblServerXHits.setObjectName("lblServerXHits")
        self.gridLayout_5.addWidget(self.lblServerXHits, 4, 1, 1, 1)
        self.lblServerXMissesTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXMissesTxt.setObjectName("lblServerXMissesTxt")
        self.gridLayout_5.addWidget(self.lblServerXMissesTxt, 5, 0, 1, 1)
        self.lblServerXMisses = QtGui.QLabel(self.gbServerX)
        self.lblServerXMisses.setObjectName("lblServerXMisses")
        self.gridLayout_5.addWidget(self.lblServerXMisses, 5, 1, 1, 1)
        self.lblServerXGetsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXGetsTxt.setObjectName("lblServerXGetsTxt")
        self.gridLayout_5.addWidget(self.lblServerXGetsTxt, 6, 0, 1, 1)
        self.lblServerXGets = QtGui.QLabel(self.gbServerX)
        self.lblServerXGets.setObjectName("lblServerXGets")
        self.gridLayout_5.addWidget(self.lblServerXGets, 6, 1, 1, 1)
        self.lblServerXSetsTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXSetsTxt.setObjectName("lblServerXSetsTxt")
        self.gridLayout_5.addWidget(self.lblServerXSetsTxt, 7, 0, 1, 1)
        self.lblServerXSets = QtGui.QLabel(self.gbServerX)
        self.lblServerXSets.setObjectName("lblServerXSets")
        self.gridLayout_5.addWidget(self.lblServerXSets, 7, 1, 1, 1)
        self.lblServerXTotalSpaceTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalSpaceTxt.setObjectName("lblServerXTotalSpaceTxt")
        self.gridLayout_5.addWidget(self.lblServerXTotalSpaceTxt, 8, 0, 1, 1)
        self.lblServerXTotalSpace = QtGui.QLabel(self.gbServerX)
        self.lblServerXTotalSpace.setObjectName("lblServerXTotalSpace")
        self.gridLayout_5.addWidget(self.lblServerXTotalSpace, 8, 1, 1, 1)
        self.lblServerXFreeSpaceTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXFreeSpaceTxt.setObjectName("lblServerXFreeSpaceTxt")
        self.gridLayout_5.addWidget(self.lblServerXFreeSpaceTxt, 9, 0, 1, 1)
        self.lblServerXFreeSpace = QtGui.QLabel(self.gbServerX)
        self.lblServerXFreeSpace.setObjectName("lblServerXFreeSpace")
        self.gridLayout_5.addWidget(self.lblServerXFreeSpace, 9, 1, 1, 1)
        self.lblServerXUsedSpaceTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXUsedSpaceTxt.setObjectName("lblServerXUsedSpaceTxt")
        self.gridLayout_5.addWidget(self.lblServerXUsedSpaceTxt, 10, 0, 1, 1)
        self.lblServerXRequestRateTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXRequestRateTxt.setObjectName("lblServerXRequestRateTxt")
        self.gridLayout_5.addWidget(self.lblServerXRequestRateTxt, 11, 0, 1, 1)
        self.lblServerXUsedSpace = QtGui.QLabel(self.gbServerX)
        self.lblServerXUsedSpace.setObjectName("lblServerXUsedSpace")
        self.gridLayout_5.addWidget(self.lblServerXUsedSpace, 10, 1, 1, 1)
        self.lblServerXRequestRate = QtGui.QLabel(self.gbServerX)
        self.lblServerXRequestRate.setObjectName("lblServerXRequestRate")
        self.gridLayout_5.addWidget(self.lblServerXRequestRate, 11, 1, 1, 1)
        self.lblServerXHitRateTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXHitRateTxt.setObjectName("lblServerXHitRateTxt")
        self.gridLayout_5.addWidget(self.lblServerXHitRateTxt, 12, 0, 1, 1)
        self.lblServerXMissRateTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXMissRateTxt.setObjectName("lblServerXMissRateTxt")
        self.gridLayout_5.addWidget(self.lblServerXMissRateTxt, 13, 0, 1, 1)
        self.lblServerXSetRateTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXSetRateTxt.setObjectName("lblServerXSetRateTxt")
        self.gridLayout_5.addWidget(self.lblServerXSetRateTxt, 15, 0, 1, 1)
        self.lblServerXGetRateTxt = QtGui.QLabel(self.gbServerX)
        self.lblServerXGetRateTxt.setObjectName("lblServerXGetRateTxt")
        self.gridLayout_5.addWidget(self.lblServerXGetRateTxt, 14, 0, 1, 1)
        self.lblServerXHitRate = QtGui.QLabel(self.gbServerX)
        self.lblServerXHitRate.setObjectName("lblServerXHitRate")
        self.gridLayout_5.addWidget(self.lblServerXHitRate, 12, 1, 1, 1)
        self.lblServerXMissRate = QtGui.QLabel(self.gbServerX)
        self.lblServerXMissRate.setObjectName("lblServerXMissRate")
        self.gridLayout_5.addWidget(self.lblServerXMissRate, 13, 1, 1, 1)
        self.lblServerXGetRate = QtGui.QLabel(self.gbServerX)
        self.lblServerXGetRate.setObjectName("lblServerXGetRate")
        self.gridLayout_5.addWidget(self.lblServerXGetRate, 14, 1, 1, 1)
        self.lblServerXSetRate = QtGui.QLabel(self.gbServerX)
        self.lblServerXSetRate.setObjectName("lblServerXSetRate")
        self.gridLayout_5.addWidget(self.lblServerXSetRate, 15, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.gbServerX)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.saServerInfo.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_6.addWidget(self.saServerInfo)
        self.tabsStats.addTab(self.ServerInfo, "")
        self.verticalLayout_4.addWidget(self.tabsStats)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRefresh = QtGui.QPushButton(self.Stats)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_2.addWidget(self.btnRefresh)
        self.btnWatch = QtGui.QPushButton(self.Stats)
        self.btnWatch.setObjectName("btnWatch")
        self.horizontalLayout_2.addWidget(self.btnWatch)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.pbStats = QtGui.QProgressBar(self.Stats)
        self.pbStats.setProperty("value", 0)
        self.pbStats.setAlignment(QtCore.Qt.AlignCenter)
        self.pbStats.setObjectName("pbStats")
        self.verticalLayout_4.addWidget(self.pbStats)
        self.tabsMain.addTab(self.Stats, "")
        self.horizontalLayout_5.addWidget(self.tabsMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Servers = QtGui.QMenu(self.menubar)
        self.menu_Servers.setObjectName("menu_Servers")
        self.menu_About = QtGui.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAddClusterServer = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddClusterServer.setIcon(icon1)
        self.actionAddClusterServer.setObjectName("actionAddClusterServer")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddCluster = QtGui.QAction(MainWindow)
        self.actionAddCluster.setIcon(icon1)
        self.actionAddCluster.setObjectName("actionAddCluster")
        self.actionTest_Sub_Item = QtGui.QAction(MainWindow)
        self.actionTest_Sub_Item.setObjectName("actionTest_Sub_Item")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menu_Servers.addAction(self.actionAddClusterServer)
        self.menu_Servers.addSeparator()
        self.menu_About.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Servers.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        self.tabsMain.setCurrentIndex(0)
        self.tabsStats.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeCluster, self.tabsMain)
        MainWindow.setTabOrder(self.tabsMain, self.txtCacheKeys)
        MainWindow.setTabOrder(self.txtCacheKeys, self.btnFlushCache)
        MainWindow.setTabOrder(self.btnFlushCache, self.txtSearchKey)
        MainWindow.setTabOrder(self.txtSearchKey, self.cbRegEx)
        MainWindow.setTabOrder(self.cbRegEx, self.btnKeySearch)
        MainWindow.setTabOrder(self.btnKeySearch, self.tabsStats)
        MainWindow.setTabOrder(self.tabsStats, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.saServerInfo)
        MainWindow.setTabOrder(self.saServerInfo, self.btnRefresh)
        MainWindow.setTabOrder(self.btnRefresh, self.btnWatch)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Memcached Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.treeCluster.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.gbClearKey.setTitle(QtGui.QApplication.translate("MainWindow", "Manage Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheKeys.setText(QtGui.QApplication.translate("MainWindow", "Cache Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCacheKeys.setToolTip(QtGui.QApplication.translate("MainWindow", "Seperate Keys with \';\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGetCacheKeys.setText(QtGui.QApplication.translate("MainWindow", "Get Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelCacheKeys.setText(QtGui.QApplication.translate("MainWindow", "Delete Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFlushCache.setToolTip(QtGui.QApplication.translate("MainWindow", "Flush Keys from All Servers in Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFlushCache.setText(QtGui.QApplication.translate("MainWindow", "Flush All Server Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.gbKeySearch.setTitle(QtGui.QApplication.translate("MainWindow", "Key Search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblKeySearch.setText(QtGui.QApplication.translate("MainWindow", "Key Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbRegEx.setText(QtGui.QApplication.translate("MainWindow", "Use RegEx Search", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRegExWarning.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Note</span><span style=\" font-size:8pt;\">: RegEx searching requires that all keys be returned from all servers in the cluster before the search can be preformed. With larger clusters this can take some time.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnKeySearch.setText(QtGui.QApplication.translate("MainWindow", "Search for Key", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.MTasks), QtGui.QApplication.translate("MainWindow", "Management Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabToolTip(self.tabsMain.indexOf(self.MTasks), QtGui.QApplication.translate("MainWindow", "Cluster Management Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Slab and Key Info is currently under development. Planned for the 0.2 release.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.SKInfo), QtGui.QApplication.translate("MainWindow", "Slab && Key Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabToolTip(self.tabsMain.indexOf(self.SKInfo), QtGui.QApplication.translate("MainWindow", "Slabs, Keys, & Values", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTotals.setTitle(QtGui.QApplication.translate("MainWindow", "Totals", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentItemsTxt.setText(QtGui.QApplication.translate("MainWindow", "Current Items:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentItems.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitsTxt.setText(QtGui.QApplication.translate("MainWindow", "Hits:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHits.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissesTxt.setText(QtGui.QApplication.translate("MainWindow", "Misses:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMisses.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreeTxt.setText(QtGui.QApplication.translate("MainWindow", "Free Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFree.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsedTxt.setText(QtGui.QApplication.translate("MainWindow", "Used Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsed.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblItemsTxt.setText(QtGui.QApplication.translate("MainWindow", "All Time Items:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblItems.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConnectionsTxt.setText(QtGui.QApplication.translate("MainWindow", "All Time Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConnections.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentConnectionsTxt.setText(QtGui.QApplication.translate("MainWindow", "Current Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentConnections.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetsTxt.setText(QtGui.QApplication.translate("MainWindow", "Gets:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGets.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetsTxt.setText(QtGui.QApplication.translate("MainWindow", "Sets:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSets.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpaceTxt.setText(QtGui.QApplication.translate("MainWindow", "Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpace.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreadsTxt.setText(QtGui.QApplication.translate("MainWindow", "Total Threads:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblThreads.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEvicTxt.setText(QtGui.QApplication.translate("MainWindow", "Evictions:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEvic.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.gbRates.setTitle(QtGui.QApplication.translate("MainWindow", "Cluster Rates", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Request Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Hit Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Miss Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Set Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Get Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEvicRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Cluster Eviction Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEvicRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.gbAvgRates.setTitle(QtGui.QApplication.translate("MainWindow", "Avg Server Rates", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRateAvgTxt.setText(QtGui.QApplication.translate("MainWindow", "Avg. Server Request Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRateAvg.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRateAvgTxt.setText(QtGui.QApplication.translate("MainWindow", "Avg. Server Hit Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRateAvg.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRateAvgTxt.setText(QtGui.QApplication.translate("MainWindow", "Avg. Server Miss Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRateAvg.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetRateAvgTxt.setText(QtGui.QApplication.translate("MainWindow", "Avg. Server Get Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetRateAvg.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRateAvgTxt.setText(QtGui.QApplication.translate("MainWindow", "Avg. Server Set Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRateAvg.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.CacheInfo), QtGui.QApplication.translate("MainWindow", "Cache Info", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheUsageGraph.setText(QtGui.QApplication.translate("MainWindow", "Cache Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitsMissesGraph.setText(QtGui.QApplication.translate("MainWindow", "Hits & Misses Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGetSetGraph.setText(QtGui.QApplication.translate("MainWindow", "Gets & Set Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.Diagrams), QtGui.QApplication.translate("MainWindow", "Diagrams", None, QtGui.QApplication.UnicodeUTF8))
        self.gbServerX.setTitle(QtGui.QApplication.translate("MainWindow", "Server X", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalItemsTxt.setText(QtGui.QApplication.translate("MainWindow", "Total Items:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalItems.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXItemsTxt.setText(QtGui.QApplication.translate("MainWindow", "Current Items:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXItems.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalConnectionsTxt.setText(QtGui.QApplication.translate("MainWindow", "Total Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalConnections.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXConnectionsTxt.setText(QtGui.QApplication.translate("MainWindow", "Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXConnections.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXHitsTxt.setText(QtGui.QApplication.translate("MainWindow", "Hits:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXHits.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXMissesTxt.setText(QtGui.QApplication.translate("MainWindow", "Misses:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXMisses.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXGetsTxt.setText(QtGui.QApplication.translate("MainWindow", "Gets:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXGets.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXSetsTxt.setText(QtGui.QApplication.translate("MainWindow", "Sets:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXSets.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalSpaceTxt.setText(QtGui.QApplication.translate("MainWindow", "Total Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXTotalSpace.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXFreeSpaceTxt.setText(QtGui.QApplication.translate("MainWindow", "Free Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXFreeSpace.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXUsedSpaceTxt.setText(QtGui.QApplication.translate("MainWindow", "Used Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXRequestRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Request Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXUsedSpace.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXRequestRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXHitRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Hit Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXMissRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Miss Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXSetRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Set Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXGetRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Get Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXHitRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXMissRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXGetRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblServerXSetRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.ServerInfo), QtGui.QApplication.translate("MainWindow", "Server Information", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWatch.setText(QtGui.QApplication.translate("MainWindow", "Watch Live Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.Stats), QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabToolTip(self.tabsMain.indexOf(self.Stats), QtGui.QApplication.translate("MainWindow", "Memcached Server Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Servers.setTitle(QtGui.QApplication.translate("MainWindow", "&Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_About.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddClusterServer.setText(QtGui.QApplication.translate("MainWindow", "&Add Cluster and/or Server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Sa&ve", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddCluster.setText(QtGui.QApplication.translate("MainWindow", "Add &Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Sub_Item.setText(QtGui.QApplication.translate("MainWindow", "Test Sub Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setIconText(QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "&Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))

